services:
  goit-cc-fp:
    image: goit-cc-fp
    build: .
    ports:
      - target: 3030
        published: 3030
        protocol: tcp
        mode: host
    env_file:
      - .env
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '20M'
        max-file: '10'
